apiVersion: v1
kind: Service
metadata:
  name: backend
  labels:
    app: backend
spec:
  ports:
    - port: 80
      name: http
  clusterIP: None
  selector:
    app: backend

---

apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: backend
  labels:
    app: backend
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
        - name: backend
          image: thomasr/example-app
          imagePullPolicy: Always

          resources:
            requests:
              cpu: 10m
          # resources

          ports:
            - name: http
              containerPort: 80
          #ports

          env:
            - name: POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
          # env
        # backend
      # containers
    # spec
  # template
# spec
